### ISSUE TITLE
Helo command rejected: need fully-qualified hostname

### ISSUE THREAD

**Issue by piotr-sikora-v** [pentacent/keila#200]
Hello
I have just created new instance of Keila in docker stack.
I try to configure system mailer, but when it try to send via my mailcow instance I see error on postfix:
Apr  2 13:15:20 51912cd08cdb postfix/smtpd[478774]: NOQUEUE: reject: RCPT from krk1.ftdl.pl[195.117.15.33]: 504 5.5.2 <ca8c239c5db6>: Helo command rejected: need fully-qualified hostname; from=<xxxx@ftdl.pl> to=<xxxxx@gmail.com> proto=ESMTP helo=<ca8c239c5db6>

EDIT:
same configuration in "Senders" work perfect.

**Comment by wmnnd** [comment]
Hey, thanks for reporting this. This is stange … but it seems like it might be a configuration problem on your email server or with your system sender. Did you maybe use the IP instead of the FQDN for your system mailer?

**Comment by piotr-sikora-v** [comment]
I use "mailcow" ... this is all-in-one docker solution https://github.com/mailcow/mailcow-dockerized, and I use this for many software and there is no problems... also when I configured same settings as "Senders" in Keila and send campaning it works. Only problem is in registration and send password reset.

I use Keila in docker... so I don't configure system mailer.
Maybe I forgot some env?

Here is all my docker env from docker-compose.yaml:

```
services:
  keila:
    image: pentacent/keila:latest
    depends_on:
      - postgres
    environment:
      SECRET_KEY_BASE: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
      DB_URL: "postgres://postgres:postgres@postgres/postgres"
      URL_HOST: "xxxxxxxxxxxxxxx"
      URL_SCHEMA: "https"
      MAILER_SMTP_HOST: "poczta.ftdl.pl"
      MAILER_SMTP_USER: "xxxxxxxxxxxxxxx@ftdl.pl"
      MAILER_SMTP_PASSWORD: "xxxxxxxxxxxxxxxx"
      KEILA_USER: "vvvvvvvvvvvvv@ftdl.pl"

      DISABLE_REGISTRATION: "false"
      SECRET_KEY_BASE: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      USER_CONTENT_DIR: "/uploads"
```
