### ISSUE TITLE
Provide docker-compose configuration

### ISSUE THREAD

**Issue by pascalwengerter** [pentacent/keila#22]
I just spent an awful amount of time today trying to get the provided `pentacent/keila` running on a private server, mostly due to a messy PostgreSQL setup.

Maybe a `docker-compose.yml` in the likes of the sketch below could be useful? Would be lovely to being able to "just" run `docker-compose run -d app` and be done with the setup 😎 happy to help with it, too!

```YAML
version: "3"

services:
  app:
    image: pentacent/keila
    ...

  db:
    image: postgres:13.2
    ...
```
