### ISSUE TITLE
SMTP sender without authentication

### ISSUE THREAD

**Issue by gvansanden** [pentacent/keila#266]
Hi, I set up Keila inside my network, my smtp server relays mails from the internal network without authentication, but Keila does not support that option.
Is there a workaround and can this be added?

**Comment by gvansanden** [comment]
Running latest in docker

**Comment by cbka** [comment]
*push

**Comment by marc-bouvier** [comment]
We are using Keila to send email from a server our internal private network.

We are using PostgreSQL lookup tables.

We encounter a lot of SQL requests due to authentication.

Using a SMTPD without authentication could reduce drastically the sollicitation of the database.

**Comment by TuringTux** [comment]
If you run Docker, and don't mind having another container active, here is the workaround I just built for my setup. I provide the full files for completeness, some of this is just boilerplate which is not specific to the workaround.

<details>

<summary>Click to see <code>.env</code> and <code>docker-compose.yml</code></summary>

## `.env`

```
DB_USER=keila
DB_NAME=keila
DB_PASSWORD=ASecretPassword
KEILA_SECRET_KEY_BASE=ASecret
```


## `docker-compose.yml`

```yaml
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    # See this blog post for how this all works: https://betterprogramming.pub/using-variables-in-docker-compose-265a604c2006
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  mailrelay:
    build: .
    restart: always

  app:
    depends_on:
      - db
      - mailrelay
    image: pentacent/keila
    volumes:
      - user_upload_data:/coli/keila/uploads
    restart: always
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      KEILA_USER: initial-user@example.com
      URL_HOST: newsletter.example.com
      URL_SCHEMA: https
      MAILER_SMTP_FROM_EMAIL: newsletter@example.com
      MAILER_SMTP_HOST: mailrelay
      MAILER_SMTP_USER: alice
      MAILER_SMTP_PASSWORD: hunter2
      SECRET_KEY_BASE: ${KEILA_SECRET_KEY_BASE}
      DISABLE_REGISTRATION: true
      USER_CONTENT_DIR: /myapp/keila/uploads

volumes:
  user_upload_data: {}
  db_data: {}
```

</details>

## `Dockerfile`

```Dockerfile
FROM debian

RUN apt-get update
RUN apt-get install -y exim4
RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Trailing slash is significant: Copy all files in mail-relay/exim4/ folder into /etc/exim4/ folder
COPY mail-relay/exim4/* /etc/exim4/

COPY mail-relay/02_enable_tls_when_relaying_mails /etc/exim4/conf.d/main
COPY mail-relay/00_require_auth_before_accepting_smtp /etc/exim4/conf.d/auth

# This command uses /etc/exim4/update-exim4.conf.conf and the files in /etc/exim4/conf.d/**
# to generate the actual production configuration which is stored in /var/lib/exim4/config.autogenerated
#
# This multi-step configuration process is a Debian idiosyncracy.
RUN update-exim4.conf

# This is just there to indicate that we will expose port 25
EXPOSE 25

# See https://man.archlinux.org/man/exim.8.en
# -bd means launching in daemon mode, -bdf is daemon in foreground, -v is verbose
ENTRYPOINT ["/usr/sbin/exim", "-bdf", "-v"]
```

## Folder `mail-relay`

### `exim4/passwd`

```
alice:$6$rKvxFAB9zUuTdNU4$HYOTBu3MTc752UVKp7K5W89p2DGhgP0J2gmwhhuIDvFtvZ1EuqNmed8byvmQivp8gihwdqTgVvOMKSdodh7E10
```

(you can generate your own hashed password using `mkpasswd --method=sha512crypt`)

### `update-exim4.conf.conf`

```
dc_eximconfig_configtype='smarthost'  # mail sent by smarthost; received via SMTP or fetchmail
dc_other_hostnames=''  # Other destinations for which mail is accepted; none.
dc_local_interfaces=''  # IP addresses to listen for incoming SMTP connections; empty listens everyhwere
dc_readhost='exim-docker'
dc_relay_domains=''
dc_minimaldns='false'
dc_relay_nets=''
dc_smarthost='your-actual-mail-server-here.example.com'
CFILEMODE='644'
dc_use_split_config='true'
dc_hide_mailname='true'  # Hide local mail name in outgoing mail (so exim-docker does not appear anywhere)
dc_mailname_in_oh='true'
dc_localdelivery='mail_spool'  # mbox format in /var/mail
```

### `00_require_auth_before_accepting_smtp`

```
# See https://www.exim.org/exim-html-current/doc/html/spec_html/ch-the_plaintext_authenticator.html
# Plaintext sounds scary, but it isn't generally, although in our case it is, but actually it kinda isn't.
#
# First of all, the whole "plaintext password" thing thrown around a lot in an email context should be super-scary, because you never
# want to transmit your password in plaintext, as a man in the middle could just intercept it and use it.
#
# But: In almost every sensible mail setup, the server uses TLS to encrypt the connection as first order of business. This means that some part of
# the program will still spit out the password as entered by the user (in a very twisted sense, you can consider this "plain"), _but will spit it
# immediately into an encrypted connection_ (which no sane person would call "plaintext").
#
# => If someone tells you, they transmit passwords in plaintext, you should worry; if its a mail server, you should not worry, mail servers
# just use weird terms.
#
# BUT: We run the entire thing within Docker and can't be bothered to set up TLS, hence the AUTH_SERVER_ALLOW_NOTLS_PASSWORDS. This means
# we actually use proper plaintext (scary!). But it is only between two Docker containers, so again kinda un-scary, because if you talk to yourself
# (or almost yourself) in an otherwise empty room, you don't need to use encryption, because no one can listen anway (the room is otherwise empty!).

AUTH_SERVER_ALLOW_NOTLS_PASSWORDS = yes

plain_server:
  driver = plaintext
  public_name = PLAIN
  server_condition = "${if crypteq{$auth3}{${extract{1}{:}{${lookup{$auth2}lsearch{CONFDIR/passwd}{$value}{*:*}}}}}{1}{0}}"
  server_set_id = $auth2
  server_prompts = :
  .ifndef AUTH_SERVER_ALLOW_NOTLS_PASSWORDS
  server_advertise_condition = ${if eq{$tls_in_cipher}{}{}{*}}
  .endif
```

### `02_enable_tls_when_relaying_mails`

```
# Added as explained in https://wiki.debian.org/Exim#Enable_TLS
# To my current understanding, this is needed so that exim can work with TLS at all, and it will automatically have certain effects.
MAIN_TLS_ENABLE = yes

# One of which being that it advertises itself as being able to handle TLS on incoming connections.
# We don't want that, so we set the advertise hosts to "" (so it never advertises this ability to any host).
MAIN_TLS_ADVERTISE_HOSTS = ""

# Added as explained in https://wiki.debian.org/Exim#Communicating_with_a_smarthost
# With this option, when communicating with actual mail server (=  smarthost)
# over which we transmit all our mail, an encrypted connection is enforced.
# See also https://www.exim.org/exim-html-current/doc/html/spec_html/ch-encrypted_smtp_connections_using_tlsssl.html#SECTclientTLS
REMOTE_SMTP_SMARTHOST_HOSTS_REQUIRE_TLS = *
```

You then configure Keila to use the SMTP mailserver `mailrelay`, no encryption, user `alice`, password `hunter2`.
