### ISSUE TITLE
JavaScript Errors when deploying 0.14

### ISSUE THREAD

**Issue by kevmodrome** [pentacent/keila#269]
I've recently tried deploying 0.14 and I'm running into JS errors that stops me from, among other things, importing contacts. On all the tabbed interfaces all tabs are shown at the same time. Trying 0.13.1 it works as expected.

Here's the docker-compose I'm using:

```yaml
version: '3'
services:
  keila:
    image: 'pentacent/keila:latest'
    ports:
      - '19998:4000'
    depends_on:
      - postgres
    environment:
      SECRET_KEY_BASE: '${SECRET_KEY}'
      DB_URL: 'postgres://postgres:postgres@postgres/postgres'
      URL_HOST: '${URL_HOST}'
      MAILER_SMTP_HOST: '${MAILER_SMTP_HOST}'
      MAILER_SMTP_USER: '${MAILER_SMTP_USER}'
      MAILER_SMTP_PASSWORD: '${MAILER_SMTP_PASSWORD}'
  postgres:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres

```
