### ISSUE TITLE
Can't get images to work

### ISSUE THREAD

**Issue by DamienZaid** [pentacent/keila#341]
I have keila running via docker behind a caddy reverse proxy and can't get images to display in my emails.

```
version: "3"
services:
  keila:
    image: pentacent/keila:latest
    ports:
      - 4004:4000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KEILA_USER
      - KEILA_PASSWORD
      - SECRET_KEY_BASE
      - DB_URL
      - URL_HOST
      - URL_PATH
      - URL_SCHEMA
      - MAILER_SMTP_HOST
      - MAILER_SMTP_USER
      - MAILER_SMTP_PASSWORD
      - MAILER_SMTP_FROM_EMAIL
      - MAILER_SMTP_PORT
      - MAILER_ENABLE_SSL
      - MAILER_ENABLE_STARTTLS
      - USER_CONTENT_DIR
      - USER_CONTENT_BASE_URL
      - UPLOADS_HOST
      - CAPTCHA_PROVIDER
      - CAPTCHA_SITE_KEY
      - CAPTCHA_SECRET_KEY
      - CAPTCHA_URL
      - DISABLE_REGISTRATION
    volumes:
      - /mnt/apps/docker/keila/uploads:/uploads
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - /mnt/apps/docker/keila/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
networks: {}
```

and the .env file:
```
URL_HOST=keila.mydomain.com
URL_PATH=/
URL_SCHEMA=https

POSTGRES_DB=com-mydomain-keila
POSTGRES_USER=com-mydomain-keila
POSTGRES_PASSWORD=blahblah

SECRET_KEY_BASE=blahblah

DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

MAILER_SMTP_FROM_EMAIL=blahblah
MAILER_SMTP_HOST=blahblah
MAILER_SMTP_USER=blahblah
MAILER_SMTP_PASSWORD=blahblah
MAILER_SMTP_PORT=blahblah
MAILER_ENABLE_SSL=false
MAILER_ENABLE_STARTTLS=true
KEILA_USER=blahblah
KEILA_PASSWORD=blahblah

USER_CONTENT_DIR=/uploads
USER_CONTENT_BASE_URL=
UPLOADS_HOST=

DISABLE_REGISTRATION=true
```

I've tried using keila.mydomain.com as USER_CONTENT_BASE_URL, but then the image preview is broken even in the editor. If I leave it blank, images are shown in the preview, but emails are still without images.

Can I somehow use my caddy reverse proxy to serve those files?

Or how could I use images that are on another webhoster?
