### ISSUE TITLE
No images display in sent emails / broken image icons

### ISSUE THREAD

**Issue by dxh0w1k** [pentacent/keila#366]
``Hey there! Testing Keila out and having an issue with images. They don't display, instead posting a broken image icon in sent emails. This includes the image in the footer of the email (after the unsubscribe link, etc). 

![Screenshot_20250103_235829](https://github.com/user-attachments/assets/db98cc09-19c3-4d77-932f-7a240b6784b1)

This email is sent and from a Gmail address (the same Gmail address, for testing). I've tried different images, also no images at all (the image below the unsubscribe icon still doesn't show). Also tried different campaign editors (markdown etc). I don't see any errors in the log and the emails are otherwise sending without issue. Any idea what is going wrong here? 

I have Keila installed through Docker:

```
version: "3.9"
services:
  db:
    image: postgres:16
    container_name: Keila-DB
    hostname: keila-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/user/docker/keila/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: [db name]
      POSTGRES_USER: [user]
      POSTGRES_PASSWORD: [pass]
    restart: unless-stopped
  keila:
    image: pentacent/keila:latest
    container_name: Keila
    hostname: keila
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000
    ports:
      - 6185:4000
    volumes:
      - /home/user/docker/keila/uploads:/uploads:rw
    environment:
      SECRET_KEY_BASE: [secret]
      DB_URL: postgres://user:pass@keila-db/keila
      USER_CONTENT_DIR: /uploads
      KEILA_USER: [Gmail address]
      KEILA_PASSWORD: [password]
      URL_HOST: [domain name]
      URL_SCHEMA: https
      MAILER_SMTP_HOST: smtp.gmail.com
      MAILER_SMTP_PORT: 465
      MAILER_SMTP_USER: [Gmail address]
      MAILER_SMTP_PASSWORD: [Gmail app password]
      MAILER_SMTP_FROM_EMAIL: [Gmail address]
      MAILER_ENABLE_SSL: true
      MAILER_ENABLE_STARTTLS: false
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
```
