### ISSUE TITLE
Keila 0.17.0 fails to start due to Mix.env() undefined function error

### ISSUE THREAD

**Issue by richardguenther** [pentacent/keila#395]
I tried to update Keila from 0.16.1 to 0.17 via a docker setup

Perplexity says this portion of the logs would be enough:

-  the application fails to start due to an undefined Mix.env() function

```txt
** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
    Mix.env()
    (keila 0.17.0) lib/keila/application.ex:62: Keila.Application.maybe_fetch_updates/0
    (keila 0.17.0) lib/keila/application.ex:39: Keila.Application.start/2
```

Here my docker compose file: (it worked again, when i set the version to 0.16.1)

```yml
services:
    keila:
        image: pentacent/keila:${KEILA_VERSION}
        container_name: keila
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
            DB_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres/keila"
            URL_HOST: "${DOMAIN}"
            URL_SCHEMA: "https"
            KEILA_USER: "${KEILA_USER}"
            KEILA_PASSWORD: "${KEILA_PASSWORD}"
            MAILER_TYPE: "${MAILER_TYPE}"
            MAILER_SMTP_FROM_EMAIL: "${MAILER_SMTP_FROM_EMAIL}"
            MAILER_SMTP_HOST: "${MAILER_SMTP_HOST}"
            MAILER_SMTP_PORT: "${MAILER_SMTP_PORT}"
            MAILER_SMTP_USER: "${MAILER_SMTP_USER}"
            MAILER_SMTP_PASSWORD: "${MAILER_SMTP_PASSWORD}"
            MAILER_ENABLE_SSL: "${MAILER_ENABLE_SSL}"
            MAILER_ENABLE_STARTTLS: "${MAILER_ENABLE_STARTTLS}"
            DISABLE_REGISTRATION: "${DISABLE_REGISTRATION}"
            DISABLE_UPDATE_CHECKS: "${DISABLE_UPDATE_CHECKS}"
        volumes:
            - ./keila/uploads:/opt/app/uploads
        networks:
            - proxy
            - internal
        labels:
            traefik.enable: "true"
            traefik.docker.network: proxy
            traefik.http.routers.keila.entrypoints: websecure
            traefik.http.routers.keila.rule: Host(`${DOMAIN}`)
            traefik.http.routers.keila.tls: "true"
            traefik.http.routers.keila.middlewares: default@file
            traefik.http.services.keila.loadbalancer.server.port: 4000
        restart: always

    postgres:
        image: postgres:17-alpine
        container_name: keila-db
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: keila
        volumes:
            - ./keila/postgres_data:/var/lib/postgresql/data
        networks:
            - internal
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    proxy:
        external: true
    internal:
        driver: bridge
```
