### ISSUE TITLE
Docker Hub Image - Timezone Environment Variable please?

### ISSUE THREAD

**Issue by BloodyIron** [pentacent/keila#400]
Hey so I just noticed when I imported my contact list the date/time is way off as I'm not at UTC myself. And I could not find anywhere in the documentation about "the way" to set the Timezone for the Docker Hub Image (which is what I'm using).

So if we could get that added to the main image that would be appreciated please.

In the interim, I looked up the Alpine documentation on this topic (since this image is based on Alpine) and I'll need to add commands that run each time the Docker Image starts.

Relevant Alpine documentation: https://wiki.alpinelinux.org/wiki/Setting_the_timezone

Method outlined:

```
apk add tzdata
ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
```

Anyways, just sharing this if other people need a work-around until this gets added to the image in some way.

**Comment by BloodyIron** [comment]
Oh and for those of us who are cool Kubernetes users, this is the method I am currently using in the interim:

```
    spec:
      containers:
      - name: keila-newsletter
        image: pentacent/keila:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - apk add tzdata &&
          ln -s /usr/share/zoneinfo/America/Edmonton /etc/localtime &&
          /opt/app/bin/keila start #entrypoint
        env:
```

**Comment by BloodyIron** [comment]
Oh and for those of us who are cool Kubernetes users, this is the method I am currently using in the interim:

```
    spec:
      containers:
      - name: keila-newsletter
        image: pentacent/keila:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - apk add tzdata &&
          ln -s /usr/share/zoneinfo/America/Chicago /etc/localtime &&
          /opt/app/bin/keila start #entrypoint
        env:
```
