### ISSUE TITLE
[Documentation] How do I embed a form on my website?

### ISSUE THREAD

**Issue by proffalken** [pentacent/keila#418]
In order to enusre that the form matches the styling on my website I've copied the HTML from the form creation page, pasted it into the source of my site, and modified the style.

Unfortunately, I've obviously done something wrong somewhere as when I submit the form it takes me to the hosted version of the form on my Keila installation rather than actually adding the details.

You can see the changes that I've made at https://github.com/wyemake/website-sandbox/pull/27 and there's a preview of the site you can test at https://deploy-preview-27--lively-heliotrope-625965.netlify.app/

I suspect it's something to do with how the `h[URL]` hidden field is generated, but I can't see anything in the documentation about how to resolve this?

**Comment by wmnnd** [comment]
Here's what I'm seeing when I try to submit your form.

![Image](https://github.com/user-attachments/assets/8acaef4b-2a69-4d1f-98c7-5b9a70466fe7)

So it looks like you might be using different hCaptcha API keys for your Keila installation and for your website which is why the captcha doesn't validate.

**Comment by proffalken** [comment]
Interesting, because I don't see that error but it would make sense.

![Screenshot_2025-05-04-19-12-59-918_com.brave.browser.jpg](https://github.com/user-attachments/assets/a87173c7-2ba5-4a40-a06a-380bf5348cd9)

That's what I see, and when I complete the captcha I just get sent to another version of the form.

Let me update the key so it works with the demo uri and I'll retest

**Comment by proffalken** [comment]
Ah, ok, I see what you mean now @wmnnd 

So here's a complete recording of me filling in the form.

Note that the **first** form (with the working hCaptcha) is on the website, the **second** form (with the hCaptcha error that you posted previously) is on the Keila installation.

I would expect the **first** form (submitted on the website) to automatically go to the final screen in the recording that says "Please confirm your email", but instead it goes to the **second** form (and apparently fills it in?) and then the user needs to submit *that* form before they get the email sent.

https://github.com/user-attachments/assets/3e034c4f-6103-40e8-94ca-ef93e173daf6

**Comment by wmnnd** [comment]
Yes, like I said that's because you're using an hCaptcha site key on your website that's different from the one in your Keila installation, so the captcha you fill out on the website is not valid in your Keila instance.

**Comment by proffalken** [comment]
> Yes, like I said that's because you're using an hCaptcha site key on your website that's different from the one in your Keila installation, so the captcha you fill out on the website is not valid in your Keila instance.

Ah, ok, thanks, I'll sort that later.

**Comment by proffalken** [comment]
I checked the docker-compose file I was using and the environment variables were set correctly, but checking the logs it said that the variables were missing.

I restarted the container but that didn't do anything.

Bringing the container down completely and then starting it again removed the error from the logs even though the configuration had not changed, and the captcha error went away on the second form.

This is a step forward, however the first form *still* redirects to the second form rather than submitting the data direction, and there is nothing in the container logs to indicate why this would be:

https://github.com/user-attachments/assets/2eeaa091-fe73-451e-9bb8-0f3c000fbd72

Logs (enabling DEBUG doesn't seem to make a difference?):

```
mailout  | 14:27:30.415 request_id=GDynzBEeFvm_R_UAAAfS [info] GET /forms/nfrm_weLJnLY5
mailout  | 14:27:30.426 request_id=GDynzBEeFvm_R_UAAAfS [info] Sent 200 in 11ms
mailout  | 14:28:43.835 request_id=GDyn3SlPDpCwxrgAAAgS [info] GET /
mailout  | 14:28:43.901 request_id=GDyn3SlPDpCwxrgAAAgS [info] Sent 200 in 65ms
mailout  | 14:28:44.765 request_id=GDyn3WC3hPhxObEAAAhi [info] GET /projects/np_weLJnLY5
mailout  | 14:28:44.803 request_id=GDyn3WC3hPhxObEAAAhi [info] Sent 200 in 38ms
mailout  | 14:29:22.733 request_id=GDyn5jfMg6Py9oAAAAjC [info] POST /forms/nfrm_weLJnLY5
mailout  | 14:29:22.894 request_id=GDyn5jfMg6Py9oAAAAjC [info] Sent 400 in 161ms
mailout  | 14:31:33.507 request_id=GDyoBKqDJJ2f6PQAAAji [info] POST /forms/nfrm_weLJnLY5
mailout  | 14:31:33.612 request_id=GDyoBKqDJJ2f6PQAAAji [info] Sent 400 in 105ms
mailout  | 14:32:03.290 request_id=GDyoC5m4tLUYoegAAAjy [info] POST /forms/nfrm_weLJnLY5
mailout  | 14:32:03.400 request_id=GDyoC5m4tLUYoegAAAjy [info] Sent 400 in 110ms
```

Docker Compose (sanitised, but left with the hcaptcha key so you can see it is the same in both places):

```
services:
  kelia:
    image: pentacent/keila:latest
    restart: always
    container_name: mailout
    ports:
      - 127.0.0.1:4000:4000
    environment:
      DB_URL: postgres://<dbuser>:<dbpass>@<dbhost>:<dbport>/<databasename>
      URL_HOST: mailout.wyemake.org.uk
      URL_PORT: 443
      SECRET_KEY_BASE: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      USER_CONTENT_DIR: /uploads
      DISABLE_REGISTRATION: true
      # System mailer (SMTP)
      MAILER_TYPE: smtp 
      MAILER_SMTP_FROM_EMAIL: info@wyemake.org.uk
      MAILER_SMTP_HOST: <outbound>
      MAILER_SMTP_PORT: <port>
      MAILER_SMTP_USER: <user>
      MAILER_SMTP_PASSWORD: <password>
      MAILER_ENABLE_SSL: "false"
      MAILER_ENABLE_STARTTLS: "true"
      CAPTCHA_PROVIDER: "hcaptcha"
      CAPTCHA_SITE_KEY: "e25c1e6c-ba4a-4db0-aa5a-29ae24649f88"
      CAPTCHA_SECRET_KEY: asjdghjlsdbwnerjawnsljfkdhsjf.asn.dfashjlrawrjasjhflkas # Looking at the docs this shouldn't be needed for hcaptcha?
      LOG_LEVEL: debug

    volumes:
      - /home/ubuntu/configs/mailout/uploads:/uploads
    labels:
      - traefik.http.routers.mailout.rule=Host(`mailout.wyemake.org.uk`)
      - traefik.http.routers.mailout.tls=true
      - traefik.http.routers.mailout.tls.domains[0].main=mailout.wyemake.org.uk
      - traefik.http.routers.mailout.tls.certresolver=letsencrypt
```

Is this a use-case that isn't possible?

Note from the code in the original issue text that I **have modified the CSS, layout, and style of the form** rather than copying the HTML directly from Keila - I'd appreciate knowing if this breaks things, and if it does I'd be happy to update the documentation accordingly.
